In [1]:
print('hello')

hello

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#### about order_details table

In [155]:
order_details = pd.read_csv('order_details.csv')
order_details.head(2)

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1

In [156]:
# total rows and column
order_details.shape

(48620, 4)

In [157]:
# to check if quantity column contains 0 or -ve values
order_details[order_details['quantity'] <= 0]

Empty DataFrame
Columns: [order_details_id, order_id, pizza_id, quantity]
Index: []

In [158]:
order_details.duplicated().sum()

np.int64(0)

In [ ]:
# to check null values and datatypes
order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [160]:
# save cleaned file
order_details.to_csv('clean_order_details.csv', index=False)

********************************************************************************************

### Order table cleaning and featuring engineering

In [237]:
orders = pd.read_csv('orders.csv')
orders.head(2)

   order_id        date      time
0         1  01-01-2015  11:38:36
1         2  01-01-2015  11:57:40

In [238]:
# total rows and columns
orders.shape

(21350, 3)

In [239]:
orders.duplicated().sum()

np.int64(0)

In [240]:
# to check null values and datatypes
# here we need to change datatype of date and time columns
orders.info()
orders.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  object
 2   time      21350 non-null  object
dtypes: int64(1), object(2)
memory usage: 500.5+ KB

order_id    0
date        0
time        0
dtype: int64

In [241]:
# to combine date and time columns in new column with proper datatype
orders['datetime'] = pd.to_datetime(orders['date'] + ' ' + orders['time'], format='%d-%m-%Y %H:%M:%S')

In [242]:
orders.head(2)

   order_id        date      time            datetime
0         1  01-01-2015  11:38:36 2015-01-01 11:38:36
1         2  01-01-2015  11:57:40 2015-01-01 11:57:40

In [243]:
# to change the datatype of date column
orders['date'] = pd.to_datetime(orders['date'], format='%d-%m-%Y')

In [244]:
orders.head(2)

   order_id       date      time            datetime
0         1 2015-01-01  11:38:36 2015-01-01 11:38:36
1         2 2015-01-01  11:57:40 2015-01-01 11:57:40

In [245]:
# now here I am droping the time column because dtype of time column is object
orders = orders.drop('time', axis=1)

In [252]:
#  now i am extracting time column from datetime column
orders['time'] = orders['datetime'].dt.time
orders.head(2)

,order_id,date,time,datetime,hour,day,day_name,month,month_name,year
0,1,2015-01-01,11:38:36,2015-01-01 11:38:36,11,4,Thursday,1,January,2015
1,2,2015-01-01,11:57:40,2015-01-01 11:57:40,11,4,Thursday,1,January,2015

In [253]:
# extracting all datetime features
orders['hour'] = orders['datetime'].dt.hour
orders['day_name'] = orders['datetime'].dt.day_name()
orders['month_name'] = orders['datetime'].dt.month_name()
orders['day'] = orders['datetime'].dt.dayofweek + 1
orders['month'] = orders['datetime'].dt.month
orders['year'] = orders['datetime'].dt.year
orders.head(2)

,order_id,date,time,datetime,hour,day,day_name,month,month_name,year
0,1,2015-01-01,11:38:36,2015-01-01 11:38:36,11,4,Thursday,1,January,2015
1,2,2015-01-01,11:57:40,2015-01-01 11:57:40,11,4,Thursday,1,January,2015

In [ ]:
# reordering columns name
# orders = orders[['order_id', 'date', 'time', 'datetime', 'hour', 'day', 'day_name', 'month', 'month_name', 'year']]
# orders.head(2)

In [255]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    21350 non-null  int64
 1   date        21350 non-null  datetime64[ns]
 2   time        21350 non-null  object
 3   datetime    21350 non-null  datetime64[ns]
 4   hour        21350 non-null  int32
 5   day         21350 non-null  int32
 6   day_name    21350 non-null  object
 7   month       21350 non-null  int32
 8   month_name  21350 non-null  object
 9   year        21350 non-null  int32
dtypes: datetime64[ns](2), int32(4), int64(1), object(3)
memory usage: 1.3+ MB

In [256]:
# save cleaned file
orders.to_csv('clean_orders.csv', index=False)

***************************************************************************

### Cleaning pizza_types table

In [174]:
pizza_types = pd.read_csv('pizza_types.csv', encoding='latin1')
pizza_types.head(2)

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."

In [175]:
# total rows and columns
pizza_types.shape

(32, 4)

In [176]:
pizza_types.duplicated().sum()

np.int64(0)

In [220]:
# to check null values and datatypes
pizza_types.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_type_id  32 non-null     object
 1   name           32 non-null     object
 2   category       32 non-null     object
 3   ingredients    32 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [178]:
#  to remove all whitespaces
for col in pizza_types.select_dtypes(include='object').columns:
    pizza_types[col] = pizza_types[col].str.strip()

In [179]:
# to check category
pizza_types['category'].unique()

array(['Chicken', 'Classic', 'Supreme', 'Veggie'], dtype=object)

In [180]:
# to convert all ingrediients column in lowercase
pizza_types['ingredients'] = pizza_types['ingredients'].str.lower()

In [221]:
pizza_types.head(2)

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"barbecued chicken, red peppers, green peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"chicken, artichoke, spinach, garlic, jalapeno ..."

In [182]:
# save cleaned file
pizza_types.to_csv('clean_pizza_types.csv', index=False)

**********************************************************************

### Cleaning pizzas table

In [183]:
pizzas = pd.read_csv('pizzas.csv')
pizzas.head(2)

    pizza_id pizza_type_id size  price
0  bbq_ckn_s       bbq_ckn    S  12.75
1  bbq_ckn_m       bbq_ckn    M  16.75

In [184]:
# total rows and columns
pizzas.shape

(96, 4)

In [185]:
pizzas.duplicated().sum()

np.int64(0)

In [186]:
# to check if prize column contains 0 or -ve values
pizzas[pizzas['price'] <= 0]

Empty DataFrame
Columns: [pizza_id, pizza_type_id, size, price]
Index: []

In [187]:
pizzas.duplicated().sum()

np.int64(0)

In [188]:
# to check null values and data types
pizzas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_id       96 non-null     object
 1   pizza_type_id  96 non-null     object
 2   size           96 non-null     object
 3   price          96 non-null     float64
dtypes: float64(1), object(3)
memory usage: 3.1+ KB

In [189]:
pizzas['size'].unique()

array(['S', 'M', 'L', 'XL', 'XXL'], dtype=object)

In [190]:
# convert datatype of size column into category to define an ordered category to ensure meaningful sorting and correct visualization. 
pizzas['size'] = pizzas['size'].astype(pd.CategoricalDtype(categories=['S', 'M', 'L', 'XL', 'XXL'], ordered=True))

In [257]:
pizzas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_id       96 non-null     object
 1   pizza_type_id  96 non-null     object
 2   size           96 non-null     category
 3   price          96 non-null     float64
dtypes: category(1), float64(1), object(2)
memory usage: 2.7+ KB

In [192]:
# save cleaned file
pizzas.to_csv('clean_pizzas.csv', index=False)

## Merge all the tables

In [258]:
pizza_sales = (
    order_details
    .merge(orders, on="order_id", how="inner")
    .merge(pizzas, on="pizza_id", how="inner")
    .merge(pizza_types, on="pizza_type_id", how="inner")
)

In [264]:
pizza_sales.head(2)

,order_details_id,order_id,pizza_id,quantity,date,time,datetime,hour,day,day_name,month,month_name,year,pizza_type_id,size,price,name,category,ingredients
0,1,1,hawaiian_m,1,2015-01-01,11:38:36,2015-01-01 11:38:36,11,4,Thursday,1,January,2015,hawaiian,M,13.25,The Hawaiian Pizza,Classic,"sliced ham, pineapple, mozzarella cheese"
1,2,2,classic_dlx_m,1,2015-01-01,11:57:40,2015-01-01 11:57:40,11,4,Thursday,1,January,2015,classic_dlx,M,16.00,The Classic Deluxe Pizza,Classic,"pepperoni, mushrooms, red onions, red peppers,..."

In [260]:
pizza_sales.isna().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
date                0
time                0
datetime            0
hour                0
day                 0
day_name            0
month               0
month_name          0
year                0
pizza_type_id       0
size                0
price               0
name                0
category            0
ingredients         0
dtype: int64

In [261]:
pizza_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
 4   date              48620 non-null  datetime64[ns]
 5   time              48620 non-null  object
 6   datetime          48620 non-null  datetime64[ns]
 7   hour              48620 non-null  int32
 8   day               48620 non-null  int32
 9   day_name          48620 non-null  object
 10  month             48620 non-null  int32
 11  month_name        48620 non-null  object
 12  year              48620 non-null  int32
 13  pizza_type_id     48620 non-null  object
 14  size              48620 non-null  category
 15  price             48620 non-null  float64
 16  name              48620 non-null  object
 17  category          48620 non-null  object
 18  ingredients       48620 non-null  object
dtypes: category(1), datetime64[ns](2), float64(1), int32(4), int64(3), object(8)
memory usage: 6.0+ MB

In [230]:
# check all column_names
pizza_sales.columns

Index(['order_details_id', 'order_id', 'pizza_id', 'quantity', 'date', 'time',
       'datetime', 'hour', 'day', 'day_name', 'month', 'month_name', 'year',
       'pizza_type_id', 'size', 'price', 'name', 'category', 'ingredients'],
      dtype='object')

In [262]:
# save file
pizza_sales.to_csv('pizza_sales.csv', index=False)

In [265]:
# rename name column to pizza_name
pizza_sales.rename(columns={"name": "pizza_name","day": "day_order"}, inplace=True)

In [266]:
# create revenue column
pizza_sales['revenue'] = pizza_sales['price'] * pizza_sales['quantity']

In [267]:
# choosing specific columns which is important for dashboard
pizza_sales = pizza_sales[["order_id","datetime","hour","day_order","day_name","month","month_name","year","pizza_name","category","size","price","quantity","revenue"]]

In [268]:
pizza_sales.head(3)

,order_id,datetime,hour,day_order,day_name,month,month_name,year,pizza_name,category,size,price,quantity,revenue
0,1,2015-01-01 11:38:36,11,4,Thursday,1,January,2015,The Hawaiian Pizza,Classic,M,13.25,1,13.25
1,2,2015-01-01 11:57:40,11,4,Thursday,1,January,2015,The Classic Deluxe Pizza,Classic,M,16.00,1,16.00
2,2,2015-01-01 11:57:40,11,4,Thursday,1,January,2015,The Five Cheese Pizza,Veggie,L,18.50,1,18.50

In [269]:
# save file
pizza_sales.to_csv('clean_pizza_sales.csv', index=False)

In [272]:
# connect python notebook file to postqreSQL
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\bisht\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in c:\users\bisht\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in c:\users\bisht\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\bisht\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [277]:
# connect to postgres
from sqlalchemy import create_engine

username = "postgres"
password = "saurabh123"
host = "localhost"
port = "5432"
database = "pizza_sales"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

In [278]:
# load df into postgresql
pizza_sales.to_sql("pizza_sales",engine,if_exists="replace",index=False)

620